# Generated by Django 5.0.6 on 2026-06-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0002_alter_warehouse_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousejournalentry',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='warehousing.warehouse', verbose_name='Склад'),
        ),
    ]
